apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: saivnct/multi-server
          ports:
            - containerPort: 5000
          # Setup environment variables
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              # environment variable must be in string
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              # environment variable must be in string
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                # reference from secret object
                secretKeyRef:
                  # Name of the secret object
                  name: pgpassword
                  # key inside the secret object
                  key: PGPASSWORD

